# Generated by Django 5.1 on 2024-09-04 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro_Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True, verbose_name='Codigo de ingreso')),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Hora de entrada')),
                ('fecha_salida', models.DateTimeField(blank=True, null=True, verbose_name='Hora de salida')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='registro.carro')),
            ],
        ),
    ]
