# Generated by Django 5.1 on 2024-09-04 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_V',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=80, verbose_name='Tipo de Vehículo')),
            ],
            options={
                'verbose_name': 'Tipo de Vehículo',
                'verbose_name_plural': 'Tipos de Vehículos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombres')),
                ('lastname', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='Correo Electrónico')),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('telefono', models.CharField(max_length=9, verbose_name='Numero telefonico')),
                ('flat_number', models.CharField(max_length=50, verbose_name='Numero de departamento')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca del vehiculo')),
                ('modelo', models.CharField(max_length=150, verbose_name='Modelo del vehiculo')),
                ('color', models.CharField(max_length=90, verbose_name='Color del Vehiculo')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carros', to='registro.tipo_v')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carros', to='registro.usuario')),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
            },
        ),
    ]
